CREATE TABLE IF NOT EXISTS pedidos.cliente (
	codigo BIGINT auto_increment NOT NULL,
	nome varchar(200) NOT NULL,
	cidade varchar(50) NOT NULL,
	uf varchar(2) NOT NULL,
	CONSTRAINT cliente_pk PRIMARY KEY (codigo)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
INSERT INTO pedidos.cliente (nome, cidade, uf)
('JOÃO DOS SANTOS','IPATINGA','MG'),
('MARIA DA SILVA','SÃO PAULO','SP'),
('ANTÔNIO DA SILVA','CORITIBA','PR'),
('MARIA ABADIA','ILHEUS','BA'),
('DELICIA MINEIRA','MACAPA','AP'),
('CARLOS ALBERTO','BRASILIA','DF'),
('MARCOS MORELLO','UBERLANDIA','MG'),
('MIRANDA DA SILVA','BOITUVA','SP'),
('MARLEI DOS SANTOS','BELO HORIZONTE','MG'),
('SALVIO ABADIO','MONTE CARMELO','MG'),
('JOANA SOARES COSTA','ARAGUARI','MG'),
('JULLIAN MOREIRA','GOIÂNIA','GO'),
('RHEYLA MOREIRA','ITUMBIARA','GO'),
('ABADIO DE JESUS','FRUTAL','MG'),
('JESUS DOS SANTOS','SÃO CARLOS','SP'),
('CARME LUCIA BARROSO','ITU','SP'),
('DOUGLAS ROBERTO','PASSO FUNDO','RS'),
('ROSEMEIRE AUGUSTA','NATAL','RN'),
('HELENA BRANDÃO','VITÓRIA','ES'),
('NAYARA MARIA','RIO DE JANEIRO','RJ'),
('ANDRÉIA NASCIMENTO','FRANCA','SP');
CREATE TABLE IF NOT EXISTS pedidos.produto (
  codigo bigint(20) NOT NULL AUTO_INCREMENT,
  nome varchar(150) NOT NULL,
  valor_venda double NOT NULL DEFAULT '0',
  PRIMARY KEY (`codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
INSERT INTO pedidos.cliente (nome, valor_venda)
('BALINHA MENTA','1.25'),
('COCA-COLA 2L','3.25'),
('ÁGUA 500ML - SEM GÁS','1.80'),
('ÁGUA 500ML - COM GÁS','10.69'),
('SABÃO EM PÓ 20KG','80.98'),
('MOUSE','5.98'),
('TECLADO','7.98'),
('BOMBOM SONHO DE VALSA','0.98'),
('RODO POLITRIZ 40CM','9.99'),
('CARNE BOVINA - ACÉM - PCT 1KG','6.87'),
('CARNE BOVINA - CONTRA FILÉ - PCT 1KG','8.98'),
('CARNE SUÍNA - PERNIL - PCT 1KG','25.98'),
('CARNE BOVINA - LOMBO - PCT 1KG','28.97'),
('MANDIOCA DA ROÇA CX','37.91'),
('TOMATE CX','97.64'),
('ABOBRINHA MENINA KG','11.98'),
('LARANJA GRAÚDA KG','9.65'),
('MELANCIA PC','3.65'),
('PICOLÉ DE FRUTA','4.87'),
('PICOLÉ DE LEITE','1.98'),
('CERVEJA SKOL CX12','9.74');